version: '3.8'

services:
  # Minio service configuration
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # S3 API Port
      - "9001:9001"  # Web UI Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data  # Persist MinIO data in volume

  # FastAPI service configuration
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"  # Expose FastAPI server port
    depends_on:
      - minio  # Ensure MinIO starts before FastAPI
    environment:
      # MinIO environment variables
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
      - MINIO_BUCKET_NAME=profile-picture
      - MINIO_PUBLIC_ENDPOINT=http://localhost:9001
    volumes:
      - .:/app  # Mount the current directory into the container
    command: >
      bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  minio-data:


